module.exports = {
  /* ================= USERS ================= */
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_SUSPEND: "USER_SUSPEND",
  USER_RESTORE: "USER_RESTORE",
  USER_PERMANENT_DELETE: "USER_PERMANENT_DELETE",

  USER_ACTIVATED: "USER_ACTIVATED",
  USER_SUSPENDED: "USER_SUSPENDED",

  /* ================= SELLERS ================= */
  SELLER_APPROVE: "SELLER_APPROVE",       // legacy (keep)
  SELLER_REJECT: "SELLER_REJECT",         // legacy (keep)

  SELLER_APPROVED: "SELLER_APPROVED",
  SELLER_REJECTED: "SELLER_REJECTED",
  SELLER_VERIFIED: "SELLER_VERIFIED",

  /* ================= AUTH ================= */
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",

  /* ================= ORDERS ================= */
  ORDER_CREATE: "ORDER_CREATE",
  ORDER_UPDATE_STATUS: "ORDER_UPDATE_STATUS",
  ORDER_STATUS_UPDATED: "ORDER_STATUS_UPDATED",

  /* ================= ADMIN ================= */
  ADMIN_SETTINGS_UPDATE: "ADMIN_SETTINGS_UPDATE",
};
