module.exports = {
    USER_CREATE: "USER_CREATE",
    USER_UPDATE: "USER_UPDATE",
    USER_SUSPEND: "USER_SUSPEND",
    USER_RESTORE: "USER_RESTORE",
    USER_PERMANENT_DELETE: "USER_PERMANENT_DELETE",
  
    SELLER_APPROVE: "SELLER_APPROVE",
    SELLER_REJECT: "SELLER_REJECT",
  
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED",
  
    ORDER_CREATE: "ORDER_CREATE",
    ORDER_UPDATE_STATUS: "ORDER_UPDATE_STATUS",
  
    ADMIN_SETTINGS_UPDATE: "ADMIN_SETTINGS_UPDATE",
  };